version: '3'

services:

  db:
    image: postgres
    environment:
      - PASSWORD=${PASSWORD}
      - NAME=${NAME}
      - USER=${USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:

    env_file:
      - .env

volumes:
  pg_data: